name: E2E All tests Chrome

# Déclencheurs
on:
  workflow_dispatch:  # Permet de lancer manuellement le workflow
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
  script:
    - npm ci
    - npm start &
    - npx cypress run --browser chrome