name: E2E All tests Chrome

# Déclencheurs
on:
  workflow_dispatch:  # Permet de lancer manuellement le workflow
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

        - name: Init code
          uses: actions/checkout@v3

        - name: Installation
          run: npm ci

        - name: Init preprocessor
          run : npm install --save-dev @bahmutov/cypress-esbuild-preprocessor @badeball/cypress-cucumber-preprocessor
        - name: Upload build
          uses: actions/upload-artifact@v4
          with:
            name: build
            path: build/
  tests:
    needs: build  
    runs-on: ubuntu-latest
    steps:
    - name: Execution
      run: npx cypress run --browser chrome