name: E2E All tests Chrome

# Déclencheurs
on:
  workflow_dispatch:  # Permet de lancer manuellement le workflow
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
        - name: Installation
          run: npm install

        - name: Execution
          run: npx cypress run --browser chrome