name: E2E All tests Chrome

# Déclencheurs
on:
  workflow_dispatch:  # Permet de lancer manuellement le workflow
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

        - name: Init code
          uses: actions/checkout@v3

        - name: Installation
          run: npm ci

        - name: Init preprocessor
          run : npm install --save-dev @bahmutov/cypress-esbuild-preprocessor

        - name: Execution
          run : npm install --save-dev @bahmutov/cypress-esbuild-preprocessor