name: E2E All tests Chrome

# Déclencheurs
on:
  workflow_dispatch:  # Permet de lancer manuellement le workflow
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
        
        - name: Setup Node.js
          uses: actions/setup-node@v3

        - name: Init code
          uses: actions/checkout@v3

        - name: Installation
          run: npm ci

        - name: Execution
          run: npx cypress run --browser chrome